#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: The iCode Project 
org_summary: >  
  Teach people of all ages that they too can learn to code
org_full_description: >  
   The iCode Project was started to give free lesson plans to teachers and organize events that will hopefully spark an interst in anyone willing to learn how to code in order to better their lives and the lives of the people around them
#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: info@theicodeproject.org
#org_street_address: 1355 Market Street #Please include suite number on the line below
#org_address_suite: Suite 900
org_city:  Los Angeles
org_state: CA
#org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  91331
#org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  #(123) 456-7890

#SOCIAL MEDIA
#org_twitter_username: theicodeproject
#org_facebook_username: smartergiving
#org_instagram_username:

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: True
fiscal_sponsor_name:  The Institute for Education, Research, and Scholarships (IFERS)
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
501c3: false

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
#donorbox_campaign_name: free-template-demo
#tinyletter_username: interestingnonprofits

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: true

#THEME
#Select one of the five color schemes (default, one, two, three, or four)
theme: default

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: GQFL9RM2VAQJE
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
